// 添加购物车
export const PUSH_PRODUCT_TO_CARD = "PUSH_PRODUCT_TO_CARD"
// 增加商品数量
export const INCREMENT_PRODUCT_TO_CARD = "INCREMENT_PRODUCT_TO_CARD"
// 减少商品数量
export const DECREMENT_PRODUCT_TO_CARD = "DECREMENT_PRODUCT_TO_CARD"
// 删除商品
export const DELETE_PRODUCT_TO_CARD = "DELETE_PRODUCT_TO_CARD"
